FROM k3yake/ws-base
MAINTAINER Katsuki Miyake <3katsu3hiro@gmail.com>

#Install Tomcat
RUN cd /usr/local && \
    wget http://ftp.jaist.ac.jp/pub/apache/tomcat/tomcat-8/v8.0.22/bin/apache-tomcat-8.0.22.tar.gz && \
    tar zxvf apache-tomcat-8.0.22.tar.gz
RUN mkdir /usr/local/apache-tomcat-8.0.22/webapps/examples/countup
COPY infra/server/base/dev/countup.jsp /usr/local/apache-tomcat-8.0.22/webapps/examples/jsp/countup.jsp
#VOLUME /usr/local/apache-tomcat-8.0.22
EXPOSE 8080


#Install H2
RUN apt-get install -y unzip
RUN cd /usr/local && \
    wget http://www.h2database.com/h2-2015-04-10.zip && \
    unzip h2-2015-04-10.zip
EXPOSE 8082
COPY infra/server/base/dev/tomcatSession.sql /root/tomcatSession.sql
RUN java -cp /usr/local/h2/bin/h2*.jar org.h2.tools.RunScript -url jdbc:h2:~/test -user sa -script /root/tomcatSession.sql

#TomcatConf
COPY infra/server/base/dev/context.xml /usr/local/apache-tomcat-8.0.22/conf/context.xml
COPY infra/server/base/dev/h2-1.4.187.jar /usr/local/apache-tomcat-8.0.22/lib/h2-1.4.187.jar

#RUN Services
COPY infra/server/base/dev/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
CMD ["/usr/bin/supervisord","-n"]

