FROM ubuntu:14.04
MAINTAINER Katsuki Miyake <3katsu3hiro@gmail.com>

#config apt
RUN sed -i".bak" -e 's/\/\/us.archive.ubuntu.com/\/\/ftp.jaist.ac.jp/g'  /etc/apt/sources.list

#Install Utility
RUN apt-get update && apt-get install -y software-properties-common python-software-properties

#Install Java8
RUN \
  echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
  add-apt-repository -y ppa:webupd8team/java && \
  apt-get update && \
  apt-get install -y oracle-java8-installer && \
  rm -rf /var/lib/apt/lists/* && \
  rm -rf /var/cache/oracle-jdk8-installer

#Install supervisor
RUN apt-get update && apt-get install -y supervisor
RUN mkdir -p /var/log/supervisor

#conf timeZone
RUN echo Asia/Tokyo | sudo tee /etc/timezone && sudo dpkg-reconfigure --frontend noninteractive tzdata